export const discordEmojis = {
    numberEmojis: ['1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣', '0️⃣'],
    x: '❌',
    save: '💾',
    '<-': '◀️',
    '->': '▶️',
    help: '❔',
    musicEmojis: {
        pause: '⏸️',
        playing: '🎶',
        playOrPause: '⏯️',
        nextSong: '⏭️',
        stop: '⏹️',
        shuffle: '🔀',
        loop: '🔁',
        clear: '🧹',
    },
    problem: '⛔',
    readme: '📄',
};
