# fly.toml app configuration file generated for frosty-wave-7955 on 2023-09-17T19:25:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-wave-7955"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 0
  processes = ["app"]
