export const enum CommandsNameEnum {
  PlayCommand = 'Play Command',
  PlaylistCommand = 'Playlist Command',
  HelpCommand = 'Help Command',
  PauseCommand = 'Pause Command',
  SkipMusicCommand = 'Skip Music Command',
  DisconnectCommand = 'Disconnect Command',
  JoinChannelCommand = 'Join Channel Command',
  ClearPlaylistCommand = 'Clear Playlist Command',
  RemoveSongsFromPlaylistCommand = 'Remove Songs From Playlist Command',
  ShufflePlaylistCommand = 'Shuffle Playlist Command',
  LoopPlaylistModeCommand = 'Loop Playlist Mode Command',
  DisplayPlaylistCommand = 'Display Playlist Command',
  DiceCommand = 'Dice Command',
  ReplyCommand = 'Reply Command',
  DiceCommandToggler = 'Dice Command Toggler',
  ReplyCommandToggler = 'Reply Command Toggler',
  LogPlaylistStatusCommand = 'Log Playlist Status Command',
  PlayNowCommand = 'Play Now Command',
  ConfigServerCommand = 'Config Server Command',
  ConfigSchemaCommand = 'Config Schema Command',
  CreatePlaylistCommand = 'Create Playlist Command',
  ShowPlayListCommand = 'Show Playlist Command',
  DeletePlaylistCommand = 'Delete Playlist Command',
  UpdatePlaylistCommand = 'Update Playlist Command',
  PlayPlaylistCommand = 'Play Playlist Command',
}
